#Requires -Version 5.1
$ErrorActionPreference = "Stop"

if ($Host.Name -eq 'ConsoleHost') {
    try {
        chcp 65001 | Out-Null
        [Console]::InputEncoding = [System.Text.UTF8Encoding]::new($false)
        [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
        $OutputEncoding = [Console]::OutputEncoding
    } catch {}
}

function Resolve-RepoRoot {
    $standaloneRoot = (Resolve-Path $PSScriptRoot).Path
    $parentDir = Split-Path -Parent $standaloneRoot
    if ((Split-Path -Leaf $parentDir) -eq "tool") {
        $nestedRoot = Split-Path -Parent $parentDir
        if (Test-Path (Join-Path $nestedRoot "secrets")) {
            return $nestedRoot
        }
    }

    return $standaloneRoot
}

$RepoRoot = Resolve-RepoRoot
$ConfigDir = Join-Path $env:USERPROFILE ".feishu-codex-bridge"
$ConfigPath = Join-Path $ConfigDir "config.env"
$SecretsTemplate = Join-Path $RepoRoot "secrets\feishu_codex_bridge.env.template"
$SecretsFile = Join-Path $RepoRoot "secrets\feishu_codex_bridge.env"
$LegacySecretsTemplate = Join-Path $RepoRoot "secrets\feishu_cursor_bridge.env.template"
$LegacySecretsFile = Join-Path $RepoRoot "secrets\feishu_cursor_bridge.env"

if (-not (Test-Path $SecretsTemplate) -and (Test-Path $LegacySecretsTemplate)) {
    $SecretsTemplate = $LegacySecretsTemplate
}

if (-not (Test-Path $SecretsFile) -and (Test-Path $LegacySecretsFile)) {
    $SecretsFile = $LegacySecretsFile
    Write-Host "WARN: using legacy secrets file -> $SecretsFile"
}

function Ensure-Directory([string]$Path) {
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Force -Path $Path | Out-Null
    }
}

function Read-Dotenv([string]$Path) {
    $result = @{}
    if (-not (Test-Path $Path)) { return $result }
    Get-Content -Encoding utf8 $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $idx = $line.IndexOf("=")
        if ($idx -lt 1) { return }
        $key = $line.Substring(0, $idx).Trim()
        $value = $line.Substring($idx + 1).Trim()
        if ($value.StartsWith('"') -and $value.EndsWith('"')) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $result[$key] = $value
    }
    return $result
}

function Ensure-SecretsFile {
    if (-not (Test-Path $SecretsFile)) {
        if (-not (Test-Path $SecretsTemplate)) {
            throw "Missing template: $SecretsTemplate"
        }
        Copy-Item $SecretsTemplate $SecretsFile
        Write-Host "WARN: created secrets file -> $SecretsFile"
    } else {
        Write-Host "OK: secrets file exists -> $SecretsFile"
    }
}

function Ensure-NodeDeps {
    $node = Get-Command node -ErrorAction SilentlyContinue
    if (-not $node) { throw "node.exe not found on PATH" }
    $npm = Get-Command npm -ErrorAction SilentlyContinue
    if (-not $npm) { throw "npm not found on PATH" }

    $nodeModules = Join-Path $PSScriptRoot "node_modules"
    if (-not (Test-Path $nodeModules)) {
        Write-Host "Installing Node dependencies for feishu-codex-bridge..."
        Push-Location $PSScriptRoot
        try {
            npm install --omit=dev
        } finally {
            Pop-Location
        }
    } else {
        Write-Host "OK: node_modules exists"
    }
}

function Ensure-CodexCli {
    $codex = Get-Command codex -ErrorAction SilentlyContinue
    if (-not $codex) {
        Write-Host "WARN: codex CLI not found on PATH. Install/login Codex before starting the bridge."
        return "codex"
    }
    $version = & codex --version 2>&1
    Write-Host "OK: codex --version -> $version"
    return "codex"
}

function Ensure-BridgeConfig {
    Ensure-Directory $ConfigDir
    $envMap = Read-Dotenv $SecretsFile
    $appId = $envMap["FEISHU_APP_ID"]
    $appSecret = $envMap["FEISHU_APP_SECRET"]
    if ([string]::IsNullOrWhiteSpace($appId) -or [string]::IsNullOrWhiteSpace($appSecret)) {
        Write-Host "WARN: FEISHU_APP_ID / FEISHU_APP_SECRET missing; fill $SecretsFile before start."
        return $false
    }

    $existing = Read-Dotenv $ConfigPath
    $allowed = $envMap["ALLOWED_USER_IDS"]
    if (-not $allowed) { $allowed = $existing["ALLOWED_USER_IDS"] }
    if (-not $allowed) { $allowed = "" }

    $codexBin = $envMap["CODEX_BIN"]
    if (-not $codexBin) { $codexBin = Ensure-CodexCli }

    $defaultProject = $envMap["DEFAULT_PROJECT_PATH"]
    if (-not $defaultProject) { $defaultProject = $RepoRoot }

    $lines = @(
        "# Generated by tool/feishu-codex-bridge/setup.ps1"
        "FEISHU_APP_ID=$appId"
        "FEISHU_APP_SECRET=$appSecret"
        "ALLOWED_USER_IDS=$allowed"
        "DEFAULT_PROJECT_PATH=$($defaultProject -replace '\\', '/')"
        "CODEX_PROJECTS=$($envMap['CODEX_PROJECTS'])"
        "CODEX_PROJECT_DISCOVERY=$(if ($envMap['CODEX_PROJECT_DISCOVERY']) { $envMap['CODEX_PROJECT_DISCOVERY'] } else { 'thread-list' })"
        "CODEX_PROJECT_DISCOVERY_TIMEOUT=$(if ($envMap['CODEX_PROJECT_DISCOVERY_TIMEOUT']) { $envMap['CODEX_PROJECT_DISCOVERY_TIMEOUT'] } else { '15000' })"
        "CODEX_PROJECT_DISCOVERY_INTERVAL=$(if ($envMap['CODEX_PROJECT_DISCOVERY_INTERVAL']) { $envMap['CODEX_PROJECT_DISCOVERY_INTERVAL'] } else { '60000' })"
        "CODEX_BIN=$codexBin"
        "CODEX_MODEL=$($envMap['CODEX_MODEL'])"
        "CODEX_MODEL_CHOICES=$($envMap['CODEX_MODEL_CHOICES'])"
        "CODEX_REASONING_EFFORT=$($envMap['CODEX_REASONING_EFFORT'])"
        "CODEX_REASONING_EFFORT_CHOICES=$($envMap['CODEX_REASONING_EFFORT_CHOICES'])"
        "CODEX_PROFILE=$($envMap['CODEX_PROFILE'])"
        "CODEX_SANDBOX_MODE=$(if ($envMap['CODEX_SANDBOX_MODE']) { $envMap['CODEX_SANDBOX_MODE'] } else { 'workspace-write' })"
        "CODEX_APPROVAL_POLICY=$(if ($envMap['CODEX_APPROVAL_POLICY']) { $envMap['CODEX_APPROVAL_POLICY'] } else { 'never' })"
        "CODEX_DANGEROUS_BYPASS=$(if ($envMap['CODEX_DANGEROUS_BYPASS']) { $envMap['CODEX_DANGEROUS_BYPASS'] } else { '0' })"
        "CODEX_FULL_AUTO=$(if ($envMap['CODEX_FULL_AUTO']) { $envMap['CODEX_FULL_AUTO'] } else { '0' })"
        "CODEX_CONFIG_OVERRIDES=$($envMap['CODEX_CONFIG_OVERRIDES'])"
        "CODEX_ENABLE_WEB_SEARCH=$(if ($envMap['CODEX_ENABLE_WEB_SEARCH']) { $envMap['CODEX_ENABLE_WEB_SEARCH'] } else { '0' })"
        "STREAM_PUSH_INTERVAL=$(if ($envMap['STREAM_PUSH_INTERVAL']) { $envMap['STREAM_PUSH_INTERVAL'] } else { '5000' })"
        "TASK_TIMEOUT=$(if ($envMap['TASK_TIMEOUT']) { $envMap['TASK_TIMEOUT'] } else { '1200000' })"
        "LOG_LEVEL=$(if ($envMap['LOG_LEVEL']) { $envMap['LOG_LEVEL'] } else { 'info' })"
    )
    Set-Content -Encoding utf8 $ConfigPath ($lines -join "`n")
    Write-Host "OK: wrote bridge config -> $ConfigPath"
    return $true
}

Write-Host "=== Feishu Codex Bridge Setup ==="
Ensure-SecretsFile
Ensure-NodeDeps
$configReady = Ensure-BridgeConfig

Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Edit $SecretsFile"
Write-Host "2. Configure Feishu bot per tool/feishu-codex-bridge/FEISHU_APP_SETUP.md"
Write-Host "3. Run: codex login"
Write-Host "4. Re-run setup.ps1, then start.ps1"
if (-not $configReady) {
    exit 2
}
